"""OpenAI Client Interface for Local LLMs (llama.cpp / Ollama / LocalAI).

Handles conversation history, function calling for DuckDuckGo web search,
and streaming token buffering into sentence chunks for real-time TTS.
"""

import asyncio
import json
import logging
import re
from typing import AsyncGenerator, Dict, List, Optional
from openai import AsyncOpenAI
from config import LLMConfig
from .tools.web_search import DUCKDUCKGO_TOOL_SCHEMA, duckduckgo_web_search_async

logger = logging.getLogger(__name__)


class LLMClient:
    """Async client interface connecting to local OpenAI-compatible endpoints."""

    def __init__(self, config: Optional[LLMConfig] = None):
        self.config = config or LLMConfig()
        self.client = AsyncOpenAI(
            base_url=self.config.base_url,
            api_key=self.config.api_key,
        )
        self.messages: List[Dict[str, str]] = [
            {"role": "system", "content": self.config.system_prompt}
        ]
        self._sentence_regex = re.compile(r"(?<=[.!?\n])\s+")

    def reset_conversation(self) -> None:
        """Reset conversation history back to the base system prompt."""
        self.messages = [{"role": "system", "content": self.config.system_prompt}]
        logger.info("Conversation history reset.")

    def add_user_message(self, text: str) -> None:
        """Add a user utterance to conversation history."""
        self.messages.append({"role": "user", "content": text})
        # Maintain a rolling window of last 10 turns to avoid context overflow
        if len(self.messages) > 12:
            self.messages = [self.messages[0]] + self.messages[-10:]

    def add_assistant_message(self, text: str) -> None:
        """Add an assistant response to conversation history."""
        self.messages.append({"role": "assistant", "content": text})

    async def generate_response_stream(
        self, user_text: str
    ) -> AsyncGenerator[str, None]:
        """Process user input, execute tools if required, and stream response sentences.

        Args:
            user_text: The transcribed user input text.

        Yields:
            str: Individual complete sentences as they are generated by the LLM.
        """
        self.add_user_message(user_text)

        # Step 1: Initial call to evaluate if LLM requests a tool call (DuckDuckGo search)
        logger.info("Sending prompt to LLM: '%s'...", user_text)
        try:
            response = await self.client.chat.completions.create(
                model=self.config.model,
                messages=self.messages,
                tools=[DUCKDUCKGO_TOOL_SCHEMA],
                tool_choice="auto",
                temperature=self.config.temperature,
                max_tokens=self.config.max_tokens,
            )

            response_message = response.choices[0].message

            # Step 2: Handle Tool Calls if generated
            if response_message.tool_calls:
                # Add the assistant's tool call message to history
                self.messages.append(response_message.model_dump(exclude_none=True))

                for tool_call in response_message.tool_calls:
                    if tool_call.function.name == "web_search":
                        try:
                            args = json.loads(tool_call.function.arguments)
                            query = args.get("query", "")
                        except Exception:
                            query = user_text

                        # Execute web search
                        search_results = await duckduckgo_web_search_async(query)

                        # Append tool output to messages
                        self.messages.append(
                            {
                                "role": "tool",
                                "tool_call_id": tool_call.id,
                                "content": search_results,
                            }
                        )

            # Step 3: Stream the final response to synthesize speech sentence-by-sentence
            stream = await self.client.chat.completions.create(
                model=self.config.model,
                messages=self.messages,
                temperature=self.config.temperature,
                max_tokens=self.config.max_tokens,
                stream=True,
            )

            buffer = ""
            full_response_text = ""

            async for chunk in stream:
                if not chunk.choices:
                    continue
                delta = chunk.choices[0].delta.content or ""
                if not delta:
                    continue

                buffer += delta
                full_response_text += delta

                # Check if buffer contains completed sentences
                parts = self._sentence_regex.split(buffer)
                if len(parts) > 1:
                    # All elements except the last are completed sentences
                    for sentence in parts[:-1]:
                        s = sentence.strip()
                        if s:
                            yield s
                    # Keep remaining incomplete fragment in buffer
                    buffer = parts[-1]

            # Yield any remaining fragment at end of stream
            final_sentence = buffer.strip()
            if final_sentence:
                yield final_sentence

            # Record final assistant response in history
            self.add_assistant_message(full_response_text.strip())

        except Exception as e:
            logger.error("LLM generation error: %s", e, exc_info=True)
            yield f"I encountered an error communicating with the local language model: {e}"
